config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  namespace :admin do
    resources :communities
    resources :community_translations
    resources :events
    # resources :event_users
    resources :festival_teachers
    resources :festival_teacher_translations
    resources :festival2025_teachers
    resources :festival2025_teacher_translations
    resources :liverpool_questions
    resources :liverpool_question_translations
    # resources :posts
    resources :questions
    resources :question_translations
    resources :sites
    resources :site_festival_translations
    resources :site_translations
    resources :sitefestivals
    resources :site2025_festival_translations
    resources :site2025_festivals
    # resources :users
    resources :tickets
    resources :lotes
    resources :uploads, only: [:new, :create]
    root to: "events#index"
  end
  get 'download_images/:image_name', to: 'files#download', as: 'download_file'
  get 'show_images/:image_name', to: 'files#show', as: 'show_file'
  mount Rswag::Api::Engine => '/api-docs'
  mount Rswag::Ui::Engine => '/api-docs'
  namespace :api do
    namespace :v1 do
      resources :communities
      resources :events
      # resources :event_users
      # resources :posts
      resources :questions
      resources :sites
      # resources :users
      resources :tickets
      resources :lotes
      resources :sitefestivals
      resources :site2025_festivals
      resources :festival_teachers
      resources :festival2025_teachers
      resources :liverpool_questions
      resources :site_translations
      resources :question_translations
      resources :liverpool_question_translations
      resources :community_translations
      resources :site_festival_translations
      resources :site2025_festival_translations
      resources :festival_teacher_translations
      resources :festival2025_teacher_translations
    end
  end

  # get 'up' => 'rails/health#show', as: :rails_health_check

  get '*path', to: 'application#frontend_index_html', constraints: lambda { |request|
    !request.xhr? && request.format.html?
  }

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/community.rb
# frozen_string_literal: true

class Community < ApplicationRecord
  before_save :clean_array_fields


  private

  def clean_array_fields
    self.profile_image = profile_image.reject(&:blank?) if profile_image
    self.name = name.reject(&:blank?) if name
  end
end

app/models/community_translation.rb
# frozen_string_literal: true

class CommunityTranslation < ApplicationRecord
end

app/models/event.rb
# frozen_string_literal: true

class Event < ApplicationRecord
end

app/models/event_user.rb
# frozen_string_literal: true

class EventUser < ApplicationRecord
end

app/models/festival2025_teacher.rb
class Festival2025Teacher < ApplicationRecord
end

app/models/festival_teacher.rb
# frozen_string_literal: true

class FestivalTeacher < ApplicationRecord
end

app/models/liverpool_question.rb
# frozen_string_literal: true

class LiverpoolQuestion < ApplicationRecord
end

app/models/lote.rb
class Lote < ApplicationRecord
end

app/models/post.rb
# frozen_string_literal: true

class Post < ApplicationRecord
end

app/models/question.rb
# frozen_string_literal: true

class Question < ApplicationRecord
end

app/models/question_translation.rb
# frozen_string_literal: true

class QuestionTranslation < ApplicationRecord
end

app/models/site.rb
# frozen_string_literal: true

class Site < ApplicationRecord
end

app/models/site2025_festival.rb
class Site2025Festival < ApplicationRecord
end

app/models/site_festival_translation.rb
class SiteFestivalTranslation < ApplicationRecord
end

app/models/site_translation.rb
# frozen_string_literal: true

class SiteTranslation < ApplicationRecord
end

app/models/sitefestival.rb
# frozen_string_literal: true

class Sitefestival < ApplicationRecord
end

app/models/ticket.rb
# frozen_string_literal: true

class Ticket < ApplicationRecord
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
end

app/controllers/admin/application_controller.rb
# All Administrate controllers inherit from this
# `Administrate::ApplicationController`, making it the ideal place to put
# authentication logic or other before_actions.
#
# If you want to add pagination or other controller-level concerns,
# you're free to overwrite the RESTful controller actions.
module Admin
  class ApplicationController < Administrate::ApplicationController
    before_action :authenticate_admin

    def authenticate_admin
      http_basic_authenticate_or_request_with(
        name: ENV.fetch("ADMIN_NAME"),
        password: ENV.fetch("ADMIN_PASSWORD")
      )
    end

    def resource_params
      params.require(resource_class.model_name.param_key).
        permit(dashboard.permitted_attributes(action_name)).
        to_h.each_with_object({}) do |(key, value), result|
          result[key] = process_field(value, key)
        end
    end

    private

    def array_fields
      []
    end
    def process_field(value, field_name)
      if array_fields.include?(field_name.to_sym)
        process_array_field(value)
      elsif value.is_a?(String)
        process_string_field(value)
      else
        value
      end
    end

    def process_array_field(value)
      return [] if value.blank?

      Array(value).flat_map { |item| item.split("\n").map(&:strip) }
    end

    def process_string_field(value)
      return nil if value.blank?

      value.strip
    end

    # Override this value to specify the number of elements to display at a time
    # on index pages. Defaults to 20.
    # def records_per_page
    #   params[:per_page] || 20
    # end
  end
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::API
end

app/controllers/files_controller.rb
class FilesController < ApplicationController
  require 'net/http'

  def download
    image_name = params[:image_name]
    extension = params[:extension]
    r2_url = "https://pub-300f3c2ca8864f7c86d0abf8f5751408.r2.dev/forroliverpool/#{image_name}.#{extension}"

    uri = URI(r2_url)
    response = Net::HTTP.get_response(uri)

    if response.is_a?(Net::HTTPSuccess)
      send_data(
        response.body,
        filename: image_name + "." + extension,
        type: response.content_type,
        disposition: 'attachment'
      )
    else
      render plain: "File not found", status: :not_found
    end
  end

  def show
    image_name = params[:image_name]
    extension = params[:extension]
    object_store_url = "https://pub-300f3c2ca8864f7c86d0abf8f5751408.r2.dev/forroliverpool/#{image_name}.#{extension}"
    cached_image = Rails.cache.fetch(object_store_url, expires_in: 1.hour) do
      uri = URI(object_store_url)
      response = Net::HTTP.get_response(uri)

      if response.is_a?(Net::HTTPSuccess)
        { body: response.body, content_type: response.content_type }
      else
        nil
      end
    end

    if cached_image
      send_data cached_image[:body], type: cached_image[:content_type], disposition: 'inline'
    else
      render json: { error: "Unable to fetch image" }, status: :bad_request
    end
  end

end

app/views/admin/application/_flashes.html.erb
<%#
# Flash Partial

This partial renders flash messages on every page.

## Relevant Helpers:

- `flash`:
  Returns a hash,
  where the keys are the type of flash (alert, error, notice, etc)
  and the values are the message to be displayed.
%>

<% if flash.any? %>
  <div class="flashes">
    <% flash.each do |key, value| -%>
      <% next unless value.respond_to?(:html_safe) %>
      <div class="flash flash-<%= key %>"><%= value.html_safe %></div>
    <% end -%>
  </div>
<% end %>

app/views/admin/application/_form.html.erb
<%#
# Form Partial

This partial is rendered on a resource's `new` and `edit` pages,
and renders all form fields for a resource's editable attributes.

## Local variables:

- `page`:
  An instance of [Administrate::Page::Form][1].
  Contains helper methods to display a form,
  and knows which attributes should be displayed in the resource's form.

[1]: http://www.rubydoc.info/gems/administrate/Administrate/Page/Form
%>
<p>
  <strong>Need to upload an image?</strong>
  <a href="<%= new_admin_upload_path %>" target="_blank">Go to the upload page</a>
</p>
<%= form_for([namespace, page.resource], html: { class: "form" }) do |f| %>
  <% if page.resource.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= t(
          "administrate.form.errors",
          pluralized_errors: pluralize(page.resource.errors.count, t("administrate.form.error")),
          resource_name: display_resource_name(page.resource_name, singular: true)
        ) %>
      </h2>

      <ul>
        <% page.resource.errors.full_messages.each do |message| %>
          <li class="flash-error"><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <% page.attributes(controller.action_name).each do |title, attributes| -%>
    <fieldset class="<%= "field-unit--nested" if title.present? %>">
      <% if title.present? %>
        <legend><%= t "helpers.label.#{f.object_name}.#{title}", default: title %></legend>
      <% end %>

      <% attributes.each do |attribute| %>
        <div class="field-unit field-unit--<%= attribute.html_class %> field-unit--<%= requireness(attribute) %>">
          <%= render_field attribute, f: f %>

          <% hint_key = "administrate.field_hints.#{page.resource_name}.#{attribute.name}" %>
          <% if I18n.exists?(hint_key) -%>
            <div class="field-unit__hint">
              <%= I18n.t(hint_key) %>
            </div>
          <% end -%>
        </div>
      <% end %>
    </fieldset>
  <% end -%>

  <div class="form-actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/admin/application/_icons.html.erb
<svg hidden xmlns="http://www.w3.org/2000/svg">
  <symbol id="icon-cancel" viewBox="0 0 48 48">
    <path fill-rule="evenodd" d="M24 19.757l-8.485-8.485c-.784-.783-2.047-.782-2.827 0l-1.417 1.416c-.777.777-.78 2.046.002 2.827L19.757 24l-8.485 8.485c-.783.784-.782 2.047 0 2.827l1.416 1.417c.777.777 2.046.78 2.827-.002L24 28.243l8.485 8.485c.784.783 2.047.782 2.827 0l1.417-1.416c.777-.777.78-2.046-.002-2.827L28.243 24l8.485-8.485c.783-.784.782-2.047 0-2.827l-1.416-1.417c-.777-.777-2.046-.78-2.827.002L24 19.757zM24 47c12.703 0 23-10.297 23-23S36.703 1 24 1 1 11.297 1 24s10.297 23 23 23z" />
  </symbol>

  <symbol id="icon-eyeglass" viewBox="0 0 48 48">
    <path d="M27.885 32.515c-2.864 1.966-6.333 3.116-10.07 3.116C7.976 35.63 0 27.656 0 17.817 0 7.976 7.976 0 17.816 0S35.63 7.976 35.63 17.816c0 3.736-1.15 7.205-3.115 10.07l14.53 14.53c1.278 1.277 1.275 3.352 0 4.628-1.28 1.278-3.353 1.278-4.63 0l-14.53-14.53zm-10.07-3.736c6.056 0 10.964-4.91 10.964-10.964 0-6.055-4.91-10.964-10.964-10.964-6.055 0-10.964 4.91-10.964 10.964 0 6.055 4.91 10.963 10.964 10.963z" />
  </symbol>

  <symbol id="icon-up-caret" viewBox="0 0 48 48">
    <path d="M2.988 33.02c-1.66 0-1.943-.81-.618-1.824l20-15.28c.878-.672 2.31-.67 3.188 0l20.075 15.288c1.316 1.003 1.048 1.816-.62 1.816H2.987z" />
  </symbol>
</svg>

app/views/admin/application/_javascript.html.erb
<%#
# Javascript Partial

This partial imports the necessary javascript on each page.
By default, it includes the application JS,
but each page can define additional JS sources
by providing a `content_for(:javascript)` block.
%>

<% Administrate::Engine.javascripts.each do |js_path| %>
  <%= javascript_include_tag js_path %>
<% end %>

<%= yield :javascript %>

<% if Rails.env.test? %>
  <%= javascript_tag do %>
    $.fx.off = true;
    $.ajaxSetup({ async: false });
  <% end %>
<% end %>

app/views/admin/application/_navigation.html.erb
<%#
# Navigation

This partial is used to display the navigation in Administrate.
By default, the navigation contains navigation links
for all resources in the admin dashboard,
as defined by the routes in the `admin/` namespace
%>

<nav class="navigation">
  <%= link_to(t("administrate.navigation.back_to_app"), root_url, class: "button button--alt button--nav") if defined?(root_url) %>

  <h1>SHARED</h1>
  <br>

  <%= link_to(
    "Upload Files",
    new_admin_upload_path,
    class: "navigation__link navigation__link--#{nav_link_state("uploads")}"
  ) %>

  <%= link_to(
    display_resource_name("events"),
    resource_index_route("events"),
    class: "navigation__link navigation__link--#{nav_link_state("events")}"
  ) %>

  <%= link_to(
    "FAQ",
    resource_index_route("questions"),
    class: "navigation__link navigation__link--#{nav_link_state("questions")}"
  ) %>

  <%= link_to(
    "FAQ Portuguese",
    resource_index_route("question_translations"),
    class: "navigation__link navigation__link--#{nav_link_state("question_translations")}"
  ) %>

  <br>
  <h1>MAIN WEBSITE</h1>
  <br>

  <%= link_to(
    "Home Page",
    resource_index_route("sites"),
    class: "navigation__link navigation__link--#{nav_link_state("sites")}"
  ) %>

  <%= link_to(
    "Home Page Portuguese",
    resource_index_route("site_translations"),
    class: "navigation__link navigation__link--#{nav_link_state("site_translations")}"
  ) %>

  <%= link_to(
    "Community",
    resource_index_route("communities"),
    class: "navigation__link navigation__link--#{nav_link_state("communities")}"
  ) %>

  <%= link_to(
    "Community Portuguese",
    resource_index_route("community_translations"),
    class: "navigation__link navigation__link--#{nav_link_state("community_translations")}"
  ) %>


  <br>
  <h1>2025 FESTIVAL</h1>
  <br>

  <%= link_to(
    "Festival Home Page",
    resource_index_route("site2025_festivals"),
    class: "navigation__link navigation__link--#{nav_link_state("site2025_festivals")}"
  ) %>

  <%= link_to(
    "Festival Home Page Portuguese",
    resource_index_route("site2025_festival_translations"),
    class: "navigation__link navigation__link--#{nav_link_state("site2025_festival_translations")}"
  ) %>

  <%= link_to(
    "Festival Teachers",
    resource_index_route("festival2025_teachers"),
    class: "navigation__link navigation__link--#{nav_link_state("festival2025_teachers")}"
  ) %>

  <%= link_to(
    "Festival Teachers Portuguese",
    resource_index_route("festival2025_teacher_translations"),
    class: "navigation__link navigation__link--#{nav_link_state("festival2025_teacher_translations")}"
  ) %>

  <%= link_to(
    "Liverpool Information",
    resource_index_route("liverpool_questions"),
    class: "navigation__link navigation__link--#{nav_link_state("liverpool_questions")}"
  ) %>

  <%= link_to(
    "Liverpool Information Portuguese",
    resource_index_route("liverpool_question_translations"),
    class: "navigation__link navigation__link--#{nav_link_state("liverpool_question_translations")}"
  ) %>

  <%= link_to(
    "Lotes",
    resource_index_route("lotes"),
    class: "navigation__link navigation__link--#{nav_link_state("lotes")}"
  ) %>

  <%= link_to(
    "Tickets",
    resource_index_route("tickets"),
    class: "navigation__link navigation__link--#{nav_link_state("tickets")}"
  ) %>


  <br>
  <h1>2024 FESTIVAL</h1>
  <br>


  <%= link_to(
    "Festival Home Page",
    resource_index_route("sitefestivals"),
    class: "navigation__link navigation__link--#{nav_link_state("sitefestivals")}"
  ) %>

  <%= link_to(
    "Festival Home Page Portuguese",
    resource_index_route("site_festival_translations"),
    class: "navigation__link navigation__link--#{nav_link_state("site_festival_translations")}"
  ) %>

  <%= link_to(
    "Festival Teachers",
    resource_index_route("festival_teachers"),
    class: "navigation__link navigation__link--#{nav_link_state("festival_teachers")}"
  ) %>

  <%= link_to(
    "Festival Teachers Portuguese",
    resource_index_route("festival_teacher_translations"),
    class: "navigation__link navigation__link--#{nav_link_state("festival_teacher_translations")}"
  ) %>

</nav>

app/views/admin/application/_stylesheet.html.erb
<%#
# Stylesheet Partial

This partial imports the necessary stylesheets on each page.
By default, it includes the application CSS,
but each page can define additional CSS sources
by providing a `content_for(:stylesheet)` block.
%>

<% Administrate::Engine.stylesheets.each do |css_path| %>
  <%= stylesheet_link_tag css_path %>
<% end %>

<%= yield :stylesheet %>

app/views/admin/application/edit.html.erb
<%#
# Edit

This view is the template for the edit page.

It displays a header, and renders the `_form` partial to do the heavy lifting.

## Local variables:

- `page`:
  An instance of [Administrate::Page::Form][1].
  Contains helper methods to help display a form,
  and knows which attributes should be displayed in the resource's form.

[1]: http://www.rubydoc.info/gems/administrate/Administrate/Page/Form
%>

<% content_for(:title) { t("administrate.actions.edit_resource", name: page.page_title) } %>

<header class="main-content__header">
  <h1 class="main-content__page-title">
    <%= content_for(:title) %>
  </h1>

  <div>
    <%= link_to(
      t("administrate.actions.show_resource", name: page.page_title),
      [namespace, page.resource],
      class: "button",
    ) if accessible_action?(page.resource, :show) %>
  </div>
</header>

<section class="main-content__body">
  <%= render "form", page: page %>
</section>

app/views/admin/application/new.html.erb
<%#
# New

This view is the template for the "new resource" page.
It displays a header, and then renders the `_form` partial
to do the heavy lifting.

## Local variables:

- `page`:
  An instance of [Administrate::Page::Form][1].
  Contains helper methods to help display a form,
  and knows which attributes should be displayed in the resource's form.

[1]: http://www.rubydoc.info/gems/administrate/Administrate/Page/Form
%>

<% content_for(:title) do %>
  <%= t(
    "administrate.actions.new_resource",
    name: display_resource_name(page.resource_name).titleize
  ) %>
<% end %>

<header class="main-content__header">
  <h1 class="main-content__page-title">
    <%= content_for(:title) %>
  </h1>

  <div>
    <%= link_to t("administrate.actions.back"), :back, class: "button" %>
  </div>
</header>

<section class="main-content__body">
  <%= render "form", page: page %>
</section>